# Generated by Django 4.2.5 on 2023-10-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('other', 'other')], max_length=150)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=4, max_digits=19)),
                ('num_guests', models.IntegerField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19)),
                ('cost_per_guest', models.DecimalField(blank=True, decimal_places=4, max_digits=19)),
                ('is_pinned', models.BooleanField(default=False)),
            ],
        ),
    ]
